name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3

      - name: upgrade pip
        run: pip install --upgrade pip
        
      - name: Setup Cog
        uses: replicate/setup-cog@v1
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
    
      - name: Install replicate
        run: pip install replicate

      - name: Delete unnecessary tools
        run: rm -rf /opt/hostedtoolcache
        

      - name: Push to Replicate
        run: |
          cog push r8.im/damilojohn/daforum_x
        env:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
